# Generated by Django 2.0 on 2019-02-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190219_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='red_num',
            field=models.IntegerField(default=0),
        ),
    ]
