# Generated by Django 2.0 on 2019-02-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_red_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='red_num',
        ),
    ]
